// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBksYUHQ7PlfPTadXB74QmRD9soBRgttdo',
    appId: '1:391677865695:web:bbee75b9a4737e3c3f036a',
    messagingSenderId: '391677865695',
    projectId: 'flutter-b1d06',
    authDomain: 'flutter-b1d06.firebaseapp.com',
    storageBucket: 'flutter-b1d06.firebasestorage.app',
    measurementId: 'G-5J8MB219NJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAVsKr9J7OaxDFmDK4MC_I6AJTVhnPT_M',
    appId: '1:391677865695:android:0a241ab17ecfdd773f036a',
    messagingSenderId: '391677865695',
    projectId: 'flutter-b1d06',
    storageBucket: 'flutter-b1d06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeZoiF5OxEqiy5gO7BmczbZ0JUH6bs1y0',
    appId: '1:391677865695:ios:fd1a216f424104853f036a',
    messagingSenderId: '391677865695',
    projectId: 'flutter-b1d06',
    storageBucket: 'flutter-b1d06.firebasestorage.app',
    iosBundleId: 'com.example.tp5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeZoiF5OxEqiy5gO7BmczbZ0JUH6bs1y0',
    appId: '1:391677865695:ios:fd1a216f424104853f036a',
    messagingSenderId: '391677865695',
    projectId: 'flutter-b1d06',
    storageBucket: 'flutter-b1d06.firebasestorage.app',
    iosBundleId: 'com.example.tp5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBksYUHQ7PlfPTadXB74QmRD9soBRgttdo',
    appId: '1:391677865695:web:f04ea7b0fce285ad3f036a',
    messagingSenderId: '391677865695',
    projectId: 'flutter-b1d06',
    authDomain: 'flutter-b1d06.firebaseapp.com',
    storageBucket: 'flutter-b1d06.firebasestorage.app',
    measurementId: 'G-4P1PX1QZ86',
  );
}
